### ISSUE TITLE
Release2 a partir da branch

### ISSUE THREAD

**Issue by CinthyaCavalcanti** [es-upe/info#13]
Bom dia,

Eu fiz a alteração no código e fiz o pull request. Só depois que vi a solicitação para criar as tags então, a tag release1 criei a partir da master (sem minhas alterações) e a tag release2 a partir da branch que criei (com minhas alterações). Tem algum problema fazer assim?

**Comment by jhcp** [comment]
Oi Cinthya, o release 1 precisa ter 2 idiomas (ex: pt e en), e o release 3 idiomas (ex: pt, en e es). Se você não fez o release após a primeira mudança, mas fez algum commit, é possível fazer a release referenciando commits antigas: dá uma olhada em "tagging later": https://git-scm.com/book/en/v2/Git-Basics-Tagging
