### ISSUE TITLE
Activity on Software Architecture

### ISSUE THREAD

**Issue by jhcp** [es-upe/info#14]
Please add here your team and your chapter (first come, first served)

**Comment by alexandremendonca** [comment]
Alexandre Mendonça - Selenium WebDriver

**Comment by dfsdaniel** [comment]
@jhcp Please send the full list with the topics (on the two mentioned books)

**Comment by alexandremendonca** [comment]
http://aosabook.org/en/index.html

**Comment by jhcp** [comment]
Any system described on The Architecture of Open Source Applications (volume 1 or 2), here: http://aosabook.org/en/index.html

**Comment by dfsdaniel** [comment]
Thanks. 
My choice is **Continuous Integration**.

**Comment by mariana-mxp** [comment]
Moodle. =)

2016-03-18 12:58 GMT-03:00 Daniel Ferreira notifications@github.com:

**Comment by vymz** [comment]
SnowFlock.

**Comment by valdenia** [comment]
The subject Continuous Integration will be presented by Daniel and me.

**Comment by tayds** [comment]
The subject MediaWiki will be presented by me and Cinthya
