### ISSUE TITLE
Assunto da próxima mini-prova

### ISSUE THREAD

**Issue by mariana-mxp** [es-upe/info#17]
João, qual o assunto e material que será cobrado na próxima mini-prova?

**Comment by dfsdaniel** [comment]
Olá professor, está melhor? Espero que sim...
O assunto da próxima mini-prova será o que está disponível na **WEEK 5**?
Abs!

> Software Process, by Alfonso Fuggetta and Elisabetta Di Nitto.

**Comment by alexandremendonca** [comment]
Caro João,

Gostaria de confirmar a nossa aula de amanhã e se o assunto para a mini-prova será apenas o relacionado com a WEEK 5?

Aproveito para desejar melhoras!

**Comment by jhcp** [comment]
Olá pessoal, não haverá mini-prova amanhã (terça), teremos a aula com prof. Gustavo
